[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-coontracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
